name: 'Setup Haskell'
description: 'Setup Haskell'
inputs:
  ghc-version:
    required: false
    description: 'Version of GHC to use. If set to "latest", it will always get the latest stable version.'
    default: 'latest'
  cabal-version:
    required: false
    description: 'Version of Cabal to use. If set to "latest", it will always get the latest stable version.'
    default: 'latest'
  cabal-project-file:
    required: false
    description: 'Path to the project configuration. Defaults to "cabal.project".'
    default: 'cabal.project'
runs:
  using: "composite"
  steps:

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ inputs.ghc-version }}
          cabal-version: ${{ inputs.cabal-version }}

      - name: Freeze Haskell dependencies
        run: |
          cabal v2-update
          cabal v2-freeze --project-file=${{ inputs.cabal-project-file }}
        shell: pwsh

      - name: Cache Haskell dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: haskell-${{ runner.os }}-${{ inputs.ghc-version }}-${{ hashFiles(env.CABAL_PROJECT_FREEZE_FILE) }}
          restore-keys: haskell-${{ runner.os }}-${{ inputs.ghc-version }}-
        env:
          CABAL_PROJECT_FREEZE_FILE: ${{ inputs.cabal-project-file }}.freeze
